apiVersion: skaffold/v2beta26
kind: Config
metadata:
 name: event-service
build:
 artifacts:
 - image: ngc23/events-service
   docker:
     dockerfile: Dockerfile
deploy:
 kubectl:
   manifests:
   - ./../deployments/dev/events-service/deployment.yaml